ProyectoDjango1/ProyectoDjango1/urls.py
from django.conf.urls import include
from django.contrib import admin

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views

import app.forms
import app.views


from django.contrib.auth.views import login, logout_then_login

#configuracion de media
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
##################3

from django.views.generic.base import RedirectView
from allauth.account.views import *


urlpatterns = [
    url(r'contador/', app.views.contador.as_view(), name='contador'),
    # Examples:
	url(r'^admin/', include(admin.site.urls)),
	url(r'^$',RedirectView.as_view(url='accounts/login/')),
	url(r'^denuncia/$', app.views.Denuncia, name='denuncia_view'),
	url(r'^accounts/', include('allauth.urls')),
	url(r'^mapa/$',app.views.Mapa.as_view(),name='mapa_view'),
	url(r'^comments/',include('django_comments.urls')),
	url(r'^noticia/(?P<pk>\d+)/$', app.views.Noticia, name='noticia_view'),
	url(r'^perfil/(?P<pk>\d+)/$',app.views.Perfil,name='perfil_view'),
	url(r'^actualizar/(?P<pk>\d+)/$',app.views.UpdatePerfil.as_view(),name='actualizarPerfil_view'),
	url(r'^registrar/$',app.views.RegisterPerfil.as_view(),name='registrarPerfil_view'), 
	#url(r'^registrar/(?P<pk>\d+)/$',app.views.RegisterPerfil.as_view(),name='registrarPerfil_view'), 



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoDjango1/app/models.py
"""
Definition of models.
"""

from django.db import models

from django.contrib.auth.models import User


class Usuario_m(models.Model):
	Nombre = models.OneToOneField(User,on_delete=models.CASCADE)
	Telefono = models.IntegerField(null=True, blank=True)
	Direccion = models.CharField(max_length=100,null=True, blank=True)
	Avatar = models.FileField(upload_to='avatar/%Y/%m/%d', null=True, blank=True)

	def __unicode__(self):
		return self.Nombre.username


class Denuncia_m(models.Model):
	user=models.ForeignKey(User)
	titulo=models.CharField(max_length=50)
	descripcion=models.TextField()
	latitud=models.FloatField()
	longitud=models.FloatField()
	lista_categorias=(
        (1,'Reten'),
		(2,'Bache'),
		(3,'Accidente'),
		(4,'Reparaciones'),
		(5,'Evento'),
		(6,'Otro')
        )
	categoria=models.IntegerField(choices=lista_categorias, verbose_name=u"Categoria",null=True, blank=True)
	lista_nivel=(
		(1,'Totalmente bloqueado'),
		(2,'Parcialmente bloqueado'),
		(3,'Ninguno')
		)
	nivel=models.IntegerField(choices=lista_nivel, verbose_name=u"Nivel",null=True, blank=True)

	def __unicode__(self):
		return self.titulo

class imagenes_m(models.Model):
    denunciaA=models.ForeignKey(Denuncia_m, null=True, blank=True)
    imagen=models.FileField(upload_to='img/%Y/%m/%d',null=True, blank=True)

class videos_m(models.Model):
    denunciaB=models.ForeignKey(Denuncia_m, null=True, blank=True)
    video=models.FileField(upload_to='img/%Y/%m/%d',null=True, blank=True)
	
class Comentario_m(models.Model):
	user=models.ForeignKey(User)
	denuncia=models.ForeignKey(Denuncia_m,null=True, blank=True)
	comentario=models.CharField(max_length=250)
	
	def __unicode__(self):
		return self.comentario

ProyectoDjango1/app/templates/app/actualizar.html
{% extends "app/base.html" %}


{% block content %}

<div class="container mt-5 pt-5">
	<div class="row">
		<div class="col">
			<form method="POST" class="form-control">
				{% csrf_token %}
				 {{ form.as_p }}
				 <input type="submit" value="Actualizar">
				 <input type="reset" value="Cancel">
			</form>	
		</div>
	</div>
</div>

{% endblock content %}

ProyectoDjango1/app/templates/app/contador.html
{% extends "app/base.html" %}


{% block content %}

{% for x in object_list %}
    <p>{{ forloop.counter + 10 }}</p>
{%endfor%}
{% endblock content %}

ProyectoDjango1/app/templates/app/denuncia.html
{% extends "app/base.html" %}



{% block content %}

<div id="map" class="container-fluid mt-5 pt-5 mb-5 pb-5">  </div>
<div class='map-overlay top'>
    <div class='map-overlay-inner'>      
        <div class="container mt-5 pt-5 mb-5 pb-5">
            <div class="row">
                <div class="col">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %} 
                        


                        <input type="hidden" name="user" required="" id="id_user" value="{{user.id}}">

                        <p><label for="nombre">Titulo:</label> <input type="text" name="titulo" required="" id="nombre" maxlength="50"></p>
                        <p><label for="id_descripcion">Descripcion:</label> <textarea name="descripcion" id="id_descripcion" rows="10" cols="40" required=""></textarea></p>
                        <p><label for="id_categoria">Categoria:</label> <select name="categoria" id="id_categoria">
                          <option value="" selected="">---------</option>

                          <option value="1">Reten</option>

                          <option value="2">Bache</option>

                          <option value="3">Accidente</option>

                          <option value="4">Reparaciones</option>

                          <option value="5">Evento</option>

                          <option value="6">Otro</option>

                        </select></p>
                        <p><label for="id_nivel">Nivel:</label> <select name="nivel" id="id_nivel">
                          <option value="" selected="">---------</option>

                          <option value="1">Totalmente bloqueado</option>

                          <option value="2">Parcialmente bloqueado</option>

                          <option value="3">Ninguno</option>

                        </select></p>
                        <input type="hidden" name="latitud" required="" id="lat">
                        <input type="hidden" name="longitud" required="" id="lng">
                        <br>

						<br>
						<!-- form 2 -->
						<!--{{form2.as_p}}-->
						<p>
                        <label for="id_imagen">Imagen:</label> 
                            <input type="file" name="imagenes" id="id_imagen" multiple>
                        </p>						
						<!-- form 3 -->

						{{form3.as_p}}
						<br>
                        <input type="submit" value="Registrar" onclick="obtenerCoordenadas()">
                        <input type="reset" value="Cancelar">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>




<script>

    // Note: This example requires that you consent to location sharing when
    // prompted by your browser. If you see the error "The Geolocation service
    // failed.", it means you probably did not give permission for the browser to
    // locate you.
    var marker;
    var x = 0;
    var y = 0;
    function initMap() {



        var map = new google.maps.Map(document.getElementById('map'), {
            center: { lng: -117.034670, lat: 32.514981 },
            zoom: 13


        });


        // Try HTML5 geolocation.
        if (navigator.geolocation) {

            navigator.geolocation.getCurrentPosition(function (position) {
                var pos = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                };
                /*
                var infoWindow = new google.maps.InfoWindow({map: map});
              infoWindow.setPosition(pos);
              infoWindow.setContent('Tu estas aqui.');
              map.setCenter(pos);
                */
                marker = new google.maps.Marker({
                    map: map,
                    draggable: true,
                    animation: google.maps.Animation.DROP,
                    position: { lng: pos.lng, lat: pos.lat }
                });
                map.setCenter(pos);


            }, function () {

                marker = new google.maps.Marker({
                    map: map,
                    draggable: true,
                    animation: google.maps.Animation.DROP,
                    position: { lng: -117.034670, lat: 32.514981 }
                });
                //handleLocationError(true, infoWindow, map.getCenter());

                });

        } else {

            marker = new google.maps.Marker({
                map: map,
                draggable: true,
                animation: google.maps.Animation.DROP,
                position: { lng: -117.034670, lat: 32.514981 }
            });
            // Browser doesn't support Geolocation
            //handleLocationError(false, infoWindow, map.getCenter());



        }
        marker.addListener('click', function () {
            obtenerCoordenadas();
        });

    }
    /*
          function handleLocationError(browserHasGeolocation, infoWindow, pos) {
            infoWindow.setPosition(pos);
            infoWindow.setContent(browserHasGeolocation ?
                                  'Error: The Geolocation service failed.' :
                                  'Error: Your browser doesn\'t support geolocation.');
          }*/

    function obtenerCoordenadas() {
        var marcador_coords = marker.getPosition();
        x = marcador_coords.lng();
        y = marcador_coords.lat();
        document.getElementById("lat").value = y;
        document.getElementById("lng").value = x;
    }
    obtenerCoordenadas();
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB1-teWu2BHQOmSdWhPxGi6K8eA2uCfUAg&callback=initMap">
</script>



<style>
	/* Always set the map height explicitly to define the size of the div
	 * element that contains the map. */
	#map {
	  height: 90%;
	  width: 100%;
	}
	/* Optional: Makes the sample page fill the window. */
	html, body {
	  height: 100%;
	  margin: 0;
	  padding: 0;
	}
  </style>
{% endblock content %}
	

ProyectoDjango1/app/templates/app/denuncia_repaldp_menor.html
{% extends "app/base.html" %}



{% block content %}

<div id="map">  </div>
<div class='map-overlay top'>
    <div class='map-overlay-inner'>
      

        <div class="container mt-5 pt-5 mb-5 pb-5">
            <div class="row">
                <div class="col">

                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %} 
                        


                        <input type="hidden" name="user" required="" id="id_user" value="{{user.id}}">

                        <p><label for="nombre">Titulo:</label> <input type="text" name="titulo" required="" id="nombre" maxlength="50"></p>
                        <p><label for="id_descripcion">Descripcion:</label> <textarea name="descripcion" id="id_descripcion" rows="10" cols="40" required=""></textarea></p>
                        <input type="hidden" name="latitud" required="" id="lat">
                        <input type="hidden" name="longitud" required="" id="lng">
                        <br>

                        <br>

                        <input type="submit" value="Registrar" onclick="obtenerCoordenadas()">
                        <input type="reset" value="Cancelar">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container mt-5 pt-5">
	<div class="col">
		<div class="row">
			<form method = "POST">
				{% csrf_token %}  
				{{form2.as_p}}
			
				<br>

				<input type ="submit" value = "Registrar">
				<input type ="reset" value = "Cancelar">	
			</form>
				
		</div>
	</div>
</div>

<div class="container mt-5 pt-5">
	<div class="col">
		<div class="row">
			<form method = "POST">
				{% csrf_token %}  
				{{form3.as_p}}
			
				<br>

				<input type ="submit" value = "Registrar">
				<input type ="reset" value = "Cancelar">	
			</form>
				
		</div>
	</div>
</div>


<script>

    // Note: This example requires that you consent to location sharing when
    // prompted by your browser. If you see the error "The Geolocation service
    // failed.", it means you probably did not give permission for the browser to
    // locate you.
    var marker;
    var x = 0;
    var y = 0;
    function initMap() {



        var map = new google.maps.Map(document.getElementById('map'), {
            center: { lng: -117.034670, lat: 32.514981 },
            zoom: 13


        });


        // Try HTML5 geolocation.
        if (navigator.geolocation) {

            navigator.geolocation.getCurrentPosition(function (position) {
                var pos = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                };
                /*
                var infoWindow = new google.maps.InfoWindow({map: map});
              infoWindow.setPosition(pos);
              infoWindow.setContent('Tu estas aqui.');
              map.setCenter(pos);
                */
                marker = new google.maps.Marker({
                    map: map,
                    draggable: true,
                    animation: google.maps.Animation.DROP,
                    position: { lng: pos.lng, lat: pos.lat }
                });
                map.setCenter(pos);


            }, function () {

                marker = new google.maps.Marker({
                    map: map,
                    draggable: true,
                    animation: google.maps.Animation.DROP,
                    position: { lng: -117.034670, lat: 32.514981 }
                });
                //handleLocationError(true, infoWindow, map.getCenter());

                });

        } else {

            marker = new google.maps.Marker({
                map: map,
                draggable: true,
                animation: google.maps.Animation.DROP,
                position: { lng: -117.034670, lat: 32.514981 }
            });
            // Browser doesn't support Geolocation
            //handleLocationError(false, infoWindow, map.getCenter());



        }
        marker.addListener('click', function () {
            obtenerCoordenadas();
        });

    }
    /*
          function handleLocationError(browserHasGeolocation, infoWindow, pos) {
            infoWindow.setPosition(pos);
            infoWindow.setContent(browserHasGeolocation ?
                                  'Error: The Geolocation service failed.' :
                                  'Error: Your browser doesn\'t support geolocation.');
          }*/

    function obtenerCoordenadas() {
        var marcador_coords = marker.getPosition();
        x = marcador_coords.lng();
        y = marcador_coords.lat();
        document.getElementById("lat").value = y;
        document.getElementById("lng").value = x;
    }
    obtenerCoordenadas();
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB1-teWu2BHQOmSdWhPxGi6K8eA2uCfUAg&callback=initMap">
</script>

<style>
    .map-overlay {
        font: 12px/20px 'Helvetica Neue', Arial, Helvetica, sans-serif;
        position: absolute;
        width: 200px;
        top: 0;
        left: 0;
        padding: 10px;
    }

        .map-overlay .map-overlay-inner {
            background-color: #fff;
            box-shadow: 0 1px 2px rgba(0, 0, 0, 0.10);
            border-radius: 3px;
            padding: 10px;
            margin-bottom: 10px;
        }

    .map-overlay-inner fieldset {
        border: none;
        padding: 0;
        margin: 0 0 10px;
    }

        .map-overlay-inner fieldset:last-child {
            margin: 0;
        }

    .map-overlay-inner select {
        width: 100%;
    }

    .map-overlay-inner label {
        display: block;
        font-weight: bold;
        margin: 0 0 5px;
    }

    .map-overlay-inner button {
        display: inline-block;
        width: 36px;
        height: 20px;
        border: none;
        cursor: pointer;
    }

        .map-overlay-inner button:focus {
            outline: none;
        }

        .map-overlay-inner button:hover {
            box-shadow: inset 0 0 0 3px rgba(0, 0, 0, 0.10);
        }
    /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
    #map {
        height: 100%;
    }
    /* Optional: Makes the sample page fill the window. */
    html, body {
        height: 100%;
        margin: 0;
        padding: 0;
    }

    #wrapper {
        position: relative;
    }

    #over_map {
        position: absolute;
        top: 10px;
        left: 10px;
        z-index: 99;
    }

    .right {
    }
</style>
{% endblock content %}
	

ProyectoDjango1/app/templates/app/denuncia_respaldo.html
{% extends "app/base.html" %}



{% block content %}
<!--
<div id="map">  </div>
<div class='map-overlay top'>
    <div class='map-overlay-inner'>
      

        <div class="container mt-5 pt-5 mb-5 pb-5">
            <div class="row">
                <div class="col">

                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %} 
                        


                        <input type="hidden" name="user" required="" id="id_user" value="{{user.id}}">

                        <p><label for="nombre">Titulo:</label> <input type="text" name="titulo" required="" id="nombre" maxlength="50"></p>
                        <p><label for="id_descripcion">Descripcion:</label> <textarea name="descripcion" id="id_descripcion" rows="10" cols="40" required=""></textarea></p>
                        <input type="hidden" name="latitud" required="" id="lat">
                        <input type="hidden" name="longitud" required="" id="lng">
                        <p><label for="id_img">Imagen:</label> <input type="file" name="img" required="" id="id_img"></p>
                        <p><label for="id_video">Video:</label> <input type="file" name="video" id="id_video"></p>

                        <br>

                        <br>

                        <input type="submit" value="Registrar" onclick="obtenerCoordenadas()">
                        <input type="reset" value="Cancelar">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
-->
<div class="container mt-5 pt-5">
	<div class="col">
		<div class="row">
			<form method = "POST">
				{% csrf_token %}  
				{{form2.as_p}}
			
				<br>

				<input type ="submit" value = "Registrar">
				<input type ="reset" value = "Cancelar">	
			</form>
				
		</div>
	</div>
</div>
<script>

    // Note: This example requires that you consent to location sharing when
    // prompted by your browser. If you see the error "The Geolocation service
    // failed.", it means you probably did not give permission for the browser to
    // locate you.
    var marker;
    var x = 0;
    var y = 0;
    function initMap() {



        var map = new google.maps.Map(document.getElementById('map'), {
            center: { lng: -117.034670, lat: 32.514981 },
            zoom: 13


        });


        // Try HTML5 geolocation.
        if (navigator.geolocation) {

            navigator.geolocation.getCurrentPosition(function (position) {
                var pos = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                };
                /*
                var infoWindow = new google.maps.InfoWindow({map: map});
              infoWindow.setPosition(pos);
              infoWindow.setContent('Tu estas aqui.');
              map.setCenter(pos);
                */
                marker = new google.maps.Marker({
                    map: map,
                    draggable: true,
                    animation: google.maps.Animation.DROP,
                    position: { lng: pos.lng, lat: pos.lat }
                });
                map.setCenter(pos);


            }, function () {

                marker = new google.maps.Marker({
                    map: map,
                    draggable: true,
                    animation: google.maps.Animation.DROP,
                    position: { lng: -117.034670, lat: 32.514981 }
                });
                //handleLocationError(true, infoWindow, map.getCenter());

                });

        } else {

            marker = new google.maps.Marker({
                map: map,
                draggable: true,
                animation: google.maps.Animation.DROP,
                position: { lng: -117.034670, lat: 32.514981 }
            });
            // Browser doesn't support Geolocation
            //handleLocationError(false, infoWindow, map.getCenter());



        }
        marker.addListener('click', function () {
            obtenerCoordenadas();
        });

    }
    /*
          function handleLocationError(browserHasGeolocation, infoWindow, pos) {
            infoWindow.setPosition(pos);
            infoWindow.setContent(browserHasGeolocation ?
                                  'Error: The Geolocation service failed.' :
                                  'Error: Your browser doesn\'t support geolocation.');
          }*/

    function obtenerCoordenadas() {
        var marcador_coords = marker.getPosition();
        x = marcador_coords.lng();
        y = marcador_coords.lat();
        document.getElementById("lat").value = y;
        document.getElementById("lng").value = x;
    }
    obtenerCoordenadas();
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB1-teWu2BHQOmSdWhPxGi6K8eA2uCfUAg&callback=initMap">
</script>

<style>
    .map-overlay {
        font: 12px/20px 'Helvetica Neue', Arial, Helvetica, sans-serif;
        position: absolute;
        width: 200px;
        top: 0;
        left: 0;
        padding: 10px;
    }

        .map-overlay .map-overlay-inner {
            background-color: #fff;
            box-shadow: 0 1px 2px rgba(0, 0, 0, 0.10);
            border-radius: 3px;
            padding: 10px;
            margin-bottom: 10px;
        }

    .map-overlay-inner fieldset {
        border: none;
        padding: 0;
        margin: 0 0 10px;
    }

        .map-overlay-inner fieldset:last-child {
            margin: 0;
        }

    .map-overlay-inner select {
        width: 100%;
    }

    .map-overlay-inner label {
        display: block;
        font-weight: bold;
        margin: 0 0 5px;
    }

    .map-overlay-inner button {
        display: inline-block;
        width: 36px;
        height: 20px;
        border: none;
        cursor: pointer;
    }

        .map-overlay-inner button:focus {
            outline: none;
        }

        .map-overlay-inner button:hover {
            box-shadow: inset 0 0 0 3px rgba(0, 0, 0, 0.10);
        }
    /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
    #map {
        height: 100%;
    }
    /* Optional: Makes the sample page fill the window. */
    html, body {
        height: 100%;
        margin: 0;
        padding: 0;
    }

    #wrapper {
        position: relative;
    }

    #over_map {
        position: absolute;
        top: 10px;
        left: 10px;
        z-index: 99;
    }

    .right {
    }
</style>
{% endblock content %}
	

ProyectoDjango1/app/templates/app/index.html
{% extends "app/base.html" %}

ProyectoDjango1/app/templates/app/noticia.html
{% extends "app/base.html" %}

{% block estilos %}

<style>

		.foot{
			height: 50px;
			display: flex;
			align-items: center;
			justify-content: center;
			color: white;
		}
		.img{
			min-width: 100%;
			min-height: 200px;
			max-height: 400px;
			background: blanchedalmond;
		}

		.form_comentarios textarea {
			width: 100%;
			height: 84px;
			max-width: 100%;
			min-width: 100%;
			min-height: 84px;
			max-height: 300px;
			padding: 10px;
			font-family: 'Roboto', sans-serif;
			line-height: 30px;
			border: 1px solid #4b65d1;
			margin-bottom: 20px;
		}
</style>
{% endblock estilos %}


{% block content %}


<div class="container mt-5 pt-5">
	<div class="row">
		<div class="col-12 mt-3">
			<div class="carousel slide" id="principal-carousel" data-ride="carousel">
				<ol class="carousel-indicators">
					<li data-target="#principal-carousel" data-slid-to="0" class="active"></li>
					<li data-target="#principal-carousel" data-slid-to="1"></li>
					<li data-target="#principal-carousel" data-slid-to="2"></li>
				</ol>

				<div class="carousel-inner">
					<div class="carousel-item active">
						<img src="img/carousel1.jpg" class="w-100" alt="">
					</div>
					<div class="carousel-item">
						<img src="img/carousel2.jpg" alt="">
					</div>
					<div class="carousel-item">
						<img src="img/carousel3.jpg" alt="">
					</div>
				</div>

				<a href="#principal-carousel" class="carousel-control-prev" data-slide="prev">
					<span class="carousel-control-prev-icon" aria-hidden="true"></span>
					<span class="sr-only">Anterior</span>
				</a>

				<a href="#principal-carousel" class="carousel-control-next" data-slide="next">
					<span class="carousel-control-next-icon" aria-hidden="true"></span>
					<span class="sr-only">Siguiente</span>
				</a>
			</div>
		</div>
	</div>
</
{% for x in ctx %}
	<div class="container mt-5 pt-5">
		<div class="row">
			<div class="col-12 text-center mb-3 h1">{{x.titulo}}</div>
		
			
				<div id="carouselExampleIndicators" class=" col-12 carousel slide" data-ride="carousel">
					<ol class="carousel-indicators">
					  <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
					  <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
					  <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
					</ol>
					<div class="carousel-inner">
						<div class="carousel-item  active  ">
							<img class="d-block img img-fluid" src="http://qnimate.com/wp-content/uploads/2014/03/images2.jpg" alt="Second slide">
						</div>
						<!-- imagenes -->
						{% for y in ctx2 %}
						<div class="carousel-item ">
							<img class="d-block img img-fluid " src="{{y.img.url}}" alt="First slide">
						</div>
						{% endfor %}
		
						<!-- VIDEOS -->
						{% for z in ctx3 %}
						<div class="carousel-item">
							
							{% if z.video %}
								
								<img class="d-block w-90 img img-fluid" src="{{z.video.url}}" alt="First slide">
							{% endif %}
								
						</div>
						{% endfor %}
		
					</div>
					<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
					  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
					  <span class="sr-only">Previous</span>
					</a>
					<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
					  <span class="carousel-control-next-icon" aria-hidden="true"></span>
					  <span class="sr-only">Next</span>
					</a>
				</div>
			
			<div class="col-12 mt-5">
				<p class="h5">{{x.descripcion}}</p>
			</div>
			<div class="col-12 mt-5">
					<form method = "POST" class="form_comentarios d-flex justify-content-end flex-wrap">
						{% csrf_token %} 

						<input type="hidden" name="user" required="" id="id_user" value="{{user.id}}">

						<input type="hidden" name="denuncia" required="" id="id_denuncia" value="{{x.id}}">

						<textarea name="comentario" required id="id_comentario" maxlength="250" placeholder="Comentario"></textarea>
						
						<input type="submit" value="Comentar">
					</form>
				
			</div>
			<div class="col-12 mt-5 pb-5 mb-5">
					<h2>Comentarios</h2>
					
			
				{% for a in ctx4 %}
				<div class="media">
					
					{% for b in ctx5  %}
						{% comment %} <li>{{b.Nombre_id}}</li>
					
						<li>{{a.user_id}}</li> {% endcomment %}
						
							
					{% endfor %}
						
					{% for b in ctx5  %}
					{% ifequal b.Nombre_id a.user_id %}
						{% if b.Avatar %}
							<img class="perfil" src="{{b.Avatar.url}}" width="64px" height="64px" alt="Imagen agregada por usuario">
					
						{% else %}
							<img class="perfil" src="http://lorempixel.com/300/300/" width="64px" height="64px" alt="Imagen aleatoria">
						
						{% endif %}
					{% endifequal %}

					{% ifnotequal b.Nombre_id a.user_id %}
					{% if not b.Avatar %}
						<img class="perfil" src="http://lorempixel.com/300/300/" width="64px" height="64px" alt="Imagen aleatoria">
					{% endif %}	
				
				{% endifnotequal %}
					
				{% endfor %}
					<div class="media-body">
						<p class="nombre"><a href="{% url 'perfil_view' pk=a.user.id %}">{{a.user}}</a></p>
						<p class="comentario">
							{{a.comentario}}
						</p>
						<p>{{a.user_id}}</p>

					</div>
				</div>
				<hr>
				{% endfor %}	
									
				
					
			</div>
			
		</div>
	</div>

{% endfor%}

{% endblock content %}
	

ProyectoDjango1/app/templates/app/perfil_perfecto.html
{% extends "app/base.html" %}


{% block content %}
	<h1 class="mt-5 pt-5"> user:id {{user.id}} </h1>
	<h2>pk {{pk}}</h2>
	<h2>Desicion {{desicion}}</h2>
{{ctx}}
{% for a in ctx %}
	<li>auth_user id de ctx:  {{a.username}}</li>
{% endfor %}

{% for b in ctx2  %}
	<li>Usuario_m id_nombre de ctx:  {{b.Nombre_id}}</li>
{% endfor %}
	

<p>-----------------{{desicion}}-------{{a}}--------------------------</p>
{% if desicion %}
	<h1>Esta registrado en authUser y Usuario_m <strong>Actualizar</strong></h1>
	{% for x in ctx2 %}
	<a href="{% url 'actualizarPerfil_view' pk=x.id %}">Actualizar</a>
{% endfor %} 

		
{%else%}

	<h1>No esta registrado <strong>RegisTrar</strong></h1>
	<a href="{% url 'registrarPerfil_view' %}">Registrar</a> 
	{% endif %}

<p>---------------------------------------</p>
	<p><h4>Cuenta de&emsp;&emsp;: <strong style="text-transform:capitalize;">{{user.socialaccount_set.all.0.provider}}</strong></h4>	
	



{% endblock content %}
	